### ISSUE TITLE
python 2.7 and binary operator raise a TypeError when operand are of different type

### ISSUE THREAD

**Issue by phil-el** [Zuzu-Typ/PyGLM#10]
a = glm.vec4(4.0)
a = a + 2.0

TypeError: unsupported operand type(s) for -: 'glm::detail::tvec4' and 'float',

python 2.7 require Py_TPFLAGS_CHECKTYPES to allow to call numeric method with different types, py3 doesn't need nor define this flag.

**Comment by Zuzu-Typ** [comment]
Wow. You're my hero.
I've been growing crazy trying to figure out why it didn't work.
