### ISSUE TITLE
missing boolean operations between `bvec`

### ISSUE THREAD

**Issue by jimy-byerley** [Zuzu-Typ/PyGLM#111]
Hello,
I'm trying to use boolean vectors for boolean operations, it seems there is no such operation implemented:

```python
>>> bvec3(1,0,0) or bvec3(1,0,1)
bvec3(1,0,0)

>> bvec3(1,0,0) | bvec3(1,0,1)
TypeError: unsupported operand type(s) for |: 'glm.bvec3' and 'glm.bvec3'

>>> bvec3(1,0,0) + bvec3(1,0,1)
TypeError: unsupported operand type(s) for +: 'glm.bvec3' and 'glm.bvec3'
```

I would have expected that there would be `|` (bitwise) or `+` (boole notation or or) available as well as `&` or `*`.
If there is no operator to operate those bits bitwise, I think it doesn't really make sense to say that `bool(bvec3(0))` is `True`, and instead it would be better to say that `bvec3(0,0,0)` is `False`

Could you possibly implement `&` `|` `^` `~` for the `bvec` ?

If it makes problems to implement those new operators on `bvec` and not on on other vectors, I think that to use the usual boole's operators used in mathematics could also be satisfying (`+` for 'or', `*` for 'and', `-` for 'not')

**Comment by Zuzu-Typ** [comment]
Hi there Jimy,

you're absolutely right, without those operations the `bvec` type is practically useless.

I was wondering why they didn't exist in the original glm, but apparently they do as `&&` and `||` which correspond to `and` and `or` in Python respectively. That's probably why I overlooked them.

I'm a little short on time right now, so I'll have to do this some other time.

Until then, here's a workaround:
```Python
bvecXor = glm.notEqual

bvecNot = glm.not_

# Works using the latest PyGLM pre-release version
bvecAnd = lambda a, b: (glm.array(a) * glm.array(b))[0]

bvecOr = lambda a, b: (glm.array(a) + glm.array(b))[0]
```

Cheers,
--Zuzu_Typ--
