### ISSUE TITLE
Add support for the rotate_vector extension

### ISSUE THREAD

**Issue by mortoray** [Zuzu-Typ/PyGLM#114]
There are several GLM GTX rotate_vector functions. I see them in the source code as well, but I'm not clear how/if they are exported to Python.

How do I call any of the rotate_vector functions, such as `rotate`, `rotateX` or `orientation`?

**Comment by Zuzu-Typ** [comment]
Hi there (:

`rotate_vector` is not currently supported unfortunately.

I'm a little busy right now, but I'll try to implement the extension at my earliest convenience.

**Comment by mortoray** [comment]
No worries. I can use the other functions now to do it.

**Comment by mortoray** [comment]
Great, thank you!
