### ISSUE TITLE
compensated sum to sum large number of floats without loosing precision (like `math.fsum`)

### ISSUE THREAD

**Issue by jimy-byerley** [Zuzu-Typ/PyGLM#122]
Hello
Is there a way in glm to perform precise float summations like `math.fsum` ?
I'm sure it's possible to implement it in C using the buffer protocol and your array types,  But I'm more thinking to some way to perform it from a python iterable (to not be obliged to allocate a new list before summation).

I found [that page](http://blog.zachbjornson.com/2019/08/11/fast-float-summation.html), that explains the [kahan algorithm](https://en.wikipedia.org/wiki/Kahan_summation_algorithm) which seems very good for this.

Is there a function or tools to do this in glm ?

**Comment by Zuzu-Typ** [comment]
Hello there (: 
Unfortunately, there is no such algorithm in glm.
The only floating point precision related algorithm in glm that I know of is `fma()` (i.e. `(x*y) + z`).

Another problem is that python's floats are actually doubles. Therefore you loose precision even during creation of a vector.
Example:
```Python
>>> glm.vec3(.1).x
0.10000000149011612
```

So this would only be viable for double vectors anyway.

There is a way of implementing it though:
```Python
import math, glm

arr = glm.array([glm.dvec3(.1)] * 10)

def fsumVecs(vecs):
    arr = glm.array(vecs)
    component_count = arr.itemsize // arr.dt_size
    out = arr.element_type()
    for i in range(component_count):
        out[i] = math.fsum(arr.map(lambda x: x[i]))
    return out

fsumVecs(arr) # returns dvec(1, 1, 1)
fsumVecs(arr).x # returns 1.0
```

It's not a very elegant solution, but it works.
I should add a `split_components()` method to arrays. Then it would become easier:
```Python
def fsumVecs(vecs):
    arr = glm.array(vecs)
    # (concept)
    components = arr.split_components()
    out = arr.element_type()
    for i in range(len(components)):
        out[i] = math.fsum(components[i])
    return out
```

**Comment by Zuzu-Typ** [comment]
I added the `split_components()` method in version 2.2.0.
I think the solution is acceptable enough to close the issue (: 

Reopen if necessary.

**Comment by jimy-byerley** [comment]
Should works fine :+1: thanks !
