### ISSUE TITLE
cibuildwheel doesn't build Windows libraries

### ISSUE THREAD

**Issue by Zuzu-Typ** [Zuzu-Typ/PyGLM#125]
When cibuildwheel attempts to download Python 3.5 (32 bit), an undisclosed [error](https://travis-ci.com/github/Zuzu-Typ/PyGLM/jobs/502299591#L189-L197) occurs.

If this issue occurs only for Python 3.5, I will have to drop support for it in upcoming releases.
But before that I need to do some investigations.

**Comment by einarf** [comment]
No tears here for dropping 3.5. Dropped it for most on my libraries 6 months ago : https://endoflife.date/python

**Comment by Zuzu-Typ** [comment]
> No tears here for dropping 3.5. 

I wouldn't miss it either, but unfortunately the issue exists for all Python versions and not just 3.5.

**Comment by Zuzu-Typ** [comment]
The issue was fixed in [cibuildwheel v1.11.0](https://github.com/joerick/cibuildwheel/releases/tag/v1.11.0).
