### ISSUE TITLE
Quaternion to mat4

### ISSUE THREAD

**Issue by JMarceloCasanova** [Zuzu-Typ/PyGLM#129]
Hello!
I'm trying to convert a quaternion to mat4, but the docs only show how to do the opposite (mat4 to quat). I found [this ](https://github.com/Zuzu-Typ/PyGLM/blob/8eef32431f3def7e358bf29293df40d5adc76ca5/glm/glm/gtx/quaternion.hpp)file with the toMat4 function but I'm guessing that the bindings are missing..

Is there an alternative way to do the conversion?

**Comment by Zuzu-Typ** [comment]
Hey there (:

The function you're looking for is `mat4_cast(q: quat)`.
I didn't know about toMat4 being an alias for it.

They should work exactly equally.

Cheers
--Zuzu_Typ--

**Comment by JMarceloCasanova** [comment]
Yeah that's it. 
Thanks.
