### ISSUE TITLE
It should be possible to create matrices from C contiguous buffers

### ISSUE THREAD

**Issue by jimy-byerley** [Zuzu-Typ/PyGLM#138]
Hello, I recently figured that such a conversion this is not working anymore:
```python
# this was working in the past (not sure which version) but doesn't work anymore in the latest version
>>> glm.fmat4(np.ones((4,4), dtype='f4'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: invalid argument type(s) for mat4x4()

>>> glm.dmat4(np.ones((4,4), dtype='f8'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: invalid argument type(s) for mat4x4()

# matmul seems broken as well, it gives unexpected results
>>> np.ones((3,3), dtype='f4') @ glm.fmat3(2)  # x*2*identity  is multiplying every element by 2, good for that one
array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]], dtype=float32)
>>> glm.fmat3(2) @ np.ones((3,3), dtype='f4')   # 2*identity*x  is multiplying every element by 2, bad result
array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]], dtype=float32)

# however this is still working
>>> np.array(glm.mat4(2))
array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]], dtype=float32)
```

It's the same for every matrix dimension, and at least for `d` and `f` precision.

Do you think that it could be fixed ?
Or did something changed in the way one is supposed to convert from `np.array` (or any buffer provider) to `glm.matN` ?

thanks in advance

**Comment by Zuzu-Typ** [comment]
Hi there (: 

for some reason the author of glm decided to have matrices in column major order (also known as Fortran contiguity).
NumPy uses row major ordering (also known as C contiguity), which is the standard C-style memory layout.
In C contiguity, the memory is layed out like this:

Memory offset | Matrix index
--- | ---
0 | M[0][0]
1 | M[0][1]
2 | M[1][0]
3 | M[1][1]

In other words, the last index varies the fastest.

In Fortran contiguity it's the other way around:

Memory offset | Matrix index
--- | ---
0 | M[0][0]
1 | M[1][0]
2 | M[0][1]
3 | M[1][1]

Thus, PyGLM requests a fortran contiguous buffer, which numpy is unable to offer.

The easiest way to fix this is making your numpy matrices use fortran ordering as well.
Just add `order="F"`:
```Python
>>> glm.fmat4(np.ones((4,4), dtype='f4', order='F'))
mat4x4(( 1, 1, 1, 1 ), ( 1, 1, 1, 1 ), ( 1, 1, 1, 1 ), ( 1, 1, 1, 1 ))
```

I do think matrices should be able to convert from C contiguous buffers as well though.

Cheers
--Zuzu_Typ--

**Comment by jimy-byerley** [comment]
You're right I was missing that aspect of C versus Fortran contiguity
But then I suspect some (more or less) recent changes in pyglm made it to refuse bad buffer contiguity where it was accepting it without test before
Because I have some code that was working last Februar that was converting `numpy slice -> fmat4`. there was no issue due to contiguity because I was only using that numpy array as storage. I can reproduce the old behavior using `fmat4(myarray[i].transpose())`

But that's easy to fix on my side, I think it's better that pyglm checks for the buffer format as it does now ;)

**Comment by Zuzu-Typ** [comment]
Well, yes. That is correct. It used to be possible to convert to and from numpy arrays with C contiguity.
However, you've already mentioned the reason why this was less than ideal:
> I can reproduce the old behavior using `fmat4(myarray[i].transpose())`

Because I didn't know at the time that OpenGL, GLSL and therefore glm were using fortran memory layout (which I don't understand to this day, as they're all C libraries), the behavior was incorrect. 
During the conversion process the matrices would always be transposed.

Looking at the version history, this has been changed in version [2.0.0a3](https://github.com/Zuzu-Typ/PyGLM/wiki/Version-history#200a3).

The fortran memory layout has caused me many headaches since then.

**Comment by Zuzu-Typ** [comment]
Matrices are now compatible with C contiguous arrays.
