### ISSUE TITLE
measure_function_glm

### ISSUE THREAD

**Issue by gottfriedleibniz** [Zuzu-Typ/PyGLM#144]
In `PyGLM vs NumPy.py` have you considered compensating for how much time is spent in the NumPy/PyGLM functions versus the ancillary measurement bits: per-iteration `time.time`, formatting, printing, etc. For example, here is my dot product measurement:
```
| dot product                            |    6.623M  |    1.512M  |     4.38x |
```

Commenting out `func(*args, **kw)` and executing again:
```
| dot product                            |    8.303M  |    8.282M  |     1.00x |
```

This seems to suggest the measurement function is unintentionally a bottleneck for the libraries actual (or potential) throughput.

Thanks.

**Comment by Zuzu-Typ** [comment]
Hey there (: 

Thank you for your input!

I had this in the back of my head for a while now.
The way I used to measure the performance was very much flawed, but I never got around to fixing it.
Until now that is.

I'm now using the `timeit` library for the actual measurements, which should be far more reliable.
This also makes it easier to add new tests.

In case you're curious, here is the new [script](https://github.com/Zuzu-Typ/PyGLM/blob/better-pyglm-vs-numpy/test/PyGLM%20vs%20NumPy.py) and here is the [output](https://github.com/Zuzu-Typ/PyGLM/tree/better-pyglm-vs-numpy#speed-comparison-to-numpy).

Cheers
--Zuzu_Typ--

**Comment by gottfriedleibniz** [comment]
Nice. These ratios resemble what I was seeing locally. In my case was doing over a billion iterations of each function with some additional logic to, hopefully, ensure I was not measuring just caching effects.

For reference, here were my results:
```
+----------------------------------------+-----------+
| dot product                            |    15.50x |
+----------------------------------------+-----------+
| cross product                          |   372.65x |
+----------------------------------------+-----------+
| L2-Norm of 3 component vector          |    62.89x |
+----------------------------------------+-----------+
```
