### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [Zuzu-Typ/PyGLM#165]
Problem
---------
On aarch64, `pip install pyglm` builds the wheels from source code and then installs it. It requires the user to have a development environment installed on their system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI.

Resolution
-----------
On aarch64, `pip install pyglm` should download the wheels from PyPI.

@Zuzu-Typ, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by Zuzu-Typ** [comment]
Hello there @odidev,

sounds like a plan!
I'd be happy to provide more users with wheels.
I have not yet tried to build PyGLM on ARM systems, but if there's no technical limitations, I can't think of any reason not to supply wheels for more systems.

Thank you for the PR. I'll merge it into a development branch, test it out, maybe add even more distros and systems and try including them in the test-workflow as well.
I'll let you know when I'm done or if I get stuck.

Again, thanks for your help!

Cheers
--Zuzu_Typ--

**Comment by Zuzu-Typ** [comment]
The new wheels are out now (:
