### ISSUE TITLE
data type transformation bug

### ISSUE THREAD

**Issue by huangkun101230** [Zuzu-Typ/PyGLM#171]
Hi,

I found a bug on the Linux machine when I did some 3d transformation (windows and mac do not have this issue).

So when I want to do this,
import numpy as np
ray3d = np.array(glm.inverse(view_mat)) @ np.array(glm.inverse(proj_mat)) @ uv [this works well on the Windows and mac] but not on the linux.
On Linux, I have to do som thing like:
ray3d = np.array(glm.inverse(view_mat)).T @ np.array(glm.inverse(proj_mat)).T @ uv
to get the correct results. 
It seems like on Linux it automatically did a transpose for me.

**Comment by Zuzu-Typ** [comment]
Hi there,

this used to be a bug in PyGLM for all systems.
Could it be possible, that the version of PyGLM that's running on your Linux system is different from the ones you tested with on Windows / Mac?
You can check by running 
```shell
pip show pyglm
```
or alternatively
```Python
import glm
print(glm.version)
```

**Comment by huangkun101230** [comment]
Yes, the problem has been solved by reinstalling the pyglm. Thank you.
