### ISSUE TITLE
Adding Stub Files for Referencing

### ISSUE THREAD

**Issue by williamhCode** [Zuzu-Typ/PyGLM#182]
Just wondering if we could add some stub files, because the only thing that pyglm harder to use than numpy is that working in VScode or any editor, there's no autocomplete, syntax highlighting, and type hinting. It's going to be a lot of work but I would love to help.

**Comment by einarf** [comment]
I was observing the same issue. I'm guessing they can just be generated with stubgen? https://mypy.readthedocs.io/en/stable/stubgen.html

**Comment by Zuzu-Typ** [comment]
Yeah, this is certainly something I should add.
Unfortunately I'm currently really short on time.

I would recommend checking out Eric Soma's [pyglm-typing](https://pypi.org/project/pyglm-typing/) for the time being.

**Comment by williamhCode** [comment]
> Yeah, this is certainly something I should add. Unfortunately I'm currently really short on time.
> 
> I would recommend checking out Erik Soma's [pyglm-typing](https://pypi.org/project/pyglm-typing/) for the time being.

Thx! this seems to work fine. Ig we somehow incorporate this library into PyGLM, like maybe just making it a dependency so it gets auto installed.
