### ISSUE TITLE
Trying to utilize glm.glm_typing

### ISSUE THREAD

**Issue by Wasserwecken** [Zuzu-Typ/PyGLM#193]
I would like to reuse the defined types of the glm libary in my own methods.
Because I dont want to loose the already defined type casts.
But I am unable to import it correctly. Did I do something wrong or is it just locked?

Example one:
![image](https://user-images.githubusercontent.com/15609168/208076488-8704feb4-8428-41e9-a1dd-bc1441154143.png)

Example two:
![image](https://user-images.githubusercontent.com/15609168/208076848-a18affd5-d9b5-44a9-9982-184786a548fc.png)

**Comment by Zuzu-Typ** [comment]
Hi there @Wasserwecken,

unfortunately, `glm_typing` is not currently available as a sub-package of `glm`.
You can however use the following code for the time being:
```Python
import importlib
glm_typing = importlib.import_module("glm-stubs.glm_typing")
```
