### ISSUE TITLE
Unexpected behavior when constructing vectors from wrong-dtype numpy arrays

### ISSUE THREAD

**Issue by avdstaaij** [Zuzu-Typ/PyGLM#196]
In the wiki, it is stated that the vector objects support both construction from iterables and from objects that supports the buffer protocol (such as numpy arrays). It seems that the buffer protocol construction has precedence over the iterable construction. This makes sense, but it has an unfortunate side-effect.

When constructing an integer vector using a numpy array of integers of the wrong size, the resulting vector is not as I would expect:
```python
>>> a = np.array([1,1,1], dtype=np.int64)
>>> glm.ivec3(a)
ivec3( 1, 0, 1 )
```
On my system, `dtype=int64` is the default, so `ivec3(np.array([1,1,1]))` produces this "bug". This effect only seems to occur for integer and boolean vectors.

If the vector had used the iterable construction method here, the result would be as expected.

This effect makes combining glm and numpy quite a bit more dangerous. This "bug" is subtle and easy to miss. For safety, vectors always have to be constructed using the unpacking operator (`ivec3(*np.array([1,1,1]))`). Even worse: since arbitrary iterables may also support the buffer protocol, this precaution has to be taken in all functions that accept a generic iterable.

My feature request:
Could PyGLM be changed to only use buffer protocol construction if the types match, and use iterable construction otherwise?

**Comment by Zuzu-Typ** [comment]
Hi there @avdstaaij ,

you seem to have found a bug. 
On my system, the same code runs without issues:
```Python
>>> a = np.array([1,1,1], dtype=np.int64)
>>> glm.ivec3(a)
ivec3( 1, 1, 1 )
```

However, running the code on linux produces the error you've mentioned.
T he bug persists with any given vector size:
```Python
>>> a = numpy.array([1,1,1], dtype="int64")
>>> glm.ivec3(a)
ivec3( 1, 0, 1 )
>>> glm.i8vec3(a)
i8vec3( 1, 0, 1 )
>>> glm.i64vec3(a)
i64vec3( 1, 0, 1 )
```

I haven't been able to look at possible causes in the code yet.


The way PyGLM converts a given object to e.g. a 32-bit int vector is by following a simple checklist:
1. Is the object a number?
2. Is the type of the object a PyGLM type?
3. Does the object support the buffer protocol?
4. Is the object a tuple or list?

If the object does support the buffer protocol, PyGLM extracts its data and identifies, which PyGLM type it corresponds to. Afterwards, it uses a suitable constructor for the target type.
I.e. in your example, PyGLM would first convert the numpy array to a 64-bit int vector (i64vec3) and continue by converting that to a 32-bit int vector (ivec3). This way you can convert from any bit-width to any other bit-width as you would expect - unless there is a bug, as is the case here.

**Comment by Zuzu-Typ** [comment]
The reason for this bug is that the data given by numpy is interpreted based on its format string. On the linux platform I've tested on, the C datatype `long` appears to be 8 bytes wide, unlike on my Windows OS, where it's 4 bytes wide.
Therefore, on the Windows machine, numpy reports the format (`np.array((1,1,1), dtype=np.int64).data.format`) as `"q"` (long long) and on Linux it reports as `"l"` (long). PyGLM always interprets `"l"` as 4-bit, regardless of the actual size of `long`, according to this table: https://docs.python.org/3/library/struct.html#format-characters.  
This needs to be fixed.

**Comment by avdstaaij** [comment]
Looks like I was too eager assuming what the issue was :).
