### ISSUE TITLE
incompatible multiply type with mat4 and vec4 when vec4 is built from a scalar

### ISSUE THREAD

**Issue by phil-el** [Zuzu-Typ/PyGLM#2]
This works as expected:
x = glm.vec4(6.0)
v = glm.vec4(4.0, 4.0, 4.0, 4.0)
x * v

but this produce an exception
x = glm.vec4(6.0)
m = glm.mat4(3.0)
m * x

with python 2.7 and python 3.6, python3 give a better stack dump than 2.7
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/glm/detail/type_mat4x4.py", line 157, in \_\_mul__
    return self.row_type(value.arr.reshape(4) * self.value)
ValueError: total size of new array must be unchanged

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_glm.py", line 18, in <module>
    print(glm.mat4(3.0)*x)
  File "/usr/lib64/python3.6/site-packages/glm/detail/type_mat4x4.py", line 172, in \_\_mul__
    raise TypeError("unsupported operand type(s) for *: 'tmat4x4' and '{}'".format(type(value)))
TypeError: unsupported operand type(s) for *: 'tmat4x4' and '<class 'glm.detail.type_vec4.tvec4'>'

I see there is a lot of commented code everywhere in mat*.py to try to handle various type but perhaps a better way to handle that is in tvecX.__init__ to create a numpy array of the right size. I didn't try but what about (2/3 for tvec2/tvec3):

if type(args[0]) in dtypes:
     self.arr = numpy.array([args[0]]*4, dtype=self.dtype)

**Comment by phil-el** [comment]
Fixed by https://github.com/Zuzu-Typ/PyGLM/pull/4 though I wonder if this was some sort of optimization to use a 1 element array.

**Comment by Zuzu-Typ** [comment]
Fixed in https://github.com/Zuzu-Typ/PyGLM/commit/81cb35df863c553930e51a172cea50dd69fcc2ea .
