### ISSUE TITLE
glm.vec2 strange behaviour

### ISSUE THREAD

**Issue by gzito** [Zuzu-Typ/PyGLM#204]
Can you please explain this strange behavior when using glm.vec2 ?

```
import glm

def test1():
    print('---- test1')
    x =  57.14285659790039
    XM = 57.14285714285714
    v = glm.vec2(x, x)
    
    print(f'Before: v.x = {v.x}')
    v.x = XM
    print(f'After:  v.x = {v.x}')


def test2():
    print('---- test2')
    x =  57.14285659790039
    XM = 57.14285714285714
    
    print(f'Before: x = {x}')
    x = XM
    print(f'After:  x = {x}')

def test3():
    print('---- test3')
    x =  1.14285659790039
    XM = 1.14285714285714
    v = glm.vec2(x, x)
    
    print(f'Before: v.x = {v.x}')
    v.x = XM
    print(f'After:  v.x = {v.x}')

test1()
test2()
test3()

```

Output:
---- test1
Before: v.x = 57.14285659790039
After:  v.x = 57.14285659790039
---- test2
Before: x = 57.14285659790039
After:  x = 57.14285714285714
---- test3
Before: v.x = 1.1428565979003906
After:  v.x = 1.1428571939468384

As you can see, in test1() the value of v.x doesn't change after the assignment

Python version: 3.9.13
PyGLM version: 2.6.0

**Comment by Wasserwecken** [comment]
If the big XM number is converted to float, there is an percision error. Storing now the value of x
![image](https://user-images.githubusercontent.com/15609168/213394628-fb85244e-9d56-49f4-b04b-e4a4bf6f0b75.png)

I dont know how python is avoiding percision errors (test3).

**Comment by Zuzu-Typ** [comment]
Thanks for the explanation @Wasserwecken!

Indeed, this is normal behaviour, because floats only have 32 bits to store any given value.

I presume test3 works, because the number `1.14285714285714` has more of its float bits available for the fraction.

You could use double (64-bit) vectors for more precision. E.g. `dvec3()`
