### ISSUE TITLE
Failing to install on raspberry  - No such file or directory: 'pyglm-typing/src/glm_typing/__init__.py'

### ISSUE THREAD

**Issue by fstokic** [Zuzu-Typ/PyGLM#209]
**Environment:**
Raspberry pi 4

**Command:**
(sudo) pip3 install PyGLM
*same error for pip3 and pip

**Problem:**
When trying to install the current version (or even glm_typing or 2-6-0 branches), then I get the missing file error: 'pyglm-typing/src/glm_typing/__init__.py'

----------
----------
----------

**Output:**

sudo pip3 install PyGLM
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyGLM
  Using cached PyGLM-2.7.0.tar.gz (4.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-zi0umuir/pyglm_9a15b1c215e54713be21d5b736d4a865/setup.py", line 33, in <module>
          shutil.copy2("pyglm-typing/src/glm_typing/__init__.py", "glm-stubs/glm_typing.py")
        File "/usr/lib/python3.7/shutil.py", line 263, in copy2
          copyfile(src, dst, follow_symlinks=follow_symlinks)
        File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
          with open(src, 'rb') as fsrc:
      FileNotFoundError: [Errno 2] No such file or directory: 'pyglm-typing/src/glm_typing/__init__.py'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

----------
----------
----------

**Attempts:**
When I tried to install older branches (update-build-system or Zuzu-Typ-1-patch), then I get the missing "glm/ext/matrix_integer.hpp" error. I tried to fix it by installing libglm-dev. It helped with some missing files, but not all of them are there.
When I tried to download the master version and add glm_typing files manually and run setup, then I got the same "glm/ext/matrix_integer.hpp" missing file error eventually.
When trying to install pyglm-typing, then it tries to install PyGLM as a requirement, and then I get the same error as mentioned above.

**Comment by szabolcsdombi** [comment]
The source distribution is broken on PyPI.
It is not possible to run `pip download pyglm --no-binary=:all:` from any platform.
Raspberry would build from source.

**Comment by Zuzu-Typ** [comment]
Fixed by #219
