### ISSUE TITLE
importing glm doesnt work

### ISSUE THREAD

**Issue by rexolon** [Zuzu-Typ/PyGLM#216]
i can install it with pip, that works
but i cant import it to my projects
when i impoprt it "import glm"
i cant use it

e.g.: res = glm.vec2(1600, 900) but it gives the warning Cannot find reference 'vec2' in '__init__.py | __init__.py'

i am 100% sure i installed PyGLM and NOT glm

**Comment by Zuzu-Typ** [comment]
I suspect you're using Python 3.11, which I haven't yet published PyGLM for. 
I'm a little busy, so please remind me if I haven't published PyGLM for Python 3.11 in a week

**Comment by rexolon** [comment]
oh alright thank you :D

**Comment by Zuzu-Typ** [comment]
Nevermind, PyGLM already supports 3.11.
Are you using Python 3.12 (prerelease) perhaps?
