### ISSUE TITLE
Broken link on PyPi page

### ISSUE THREAD

**Issue by JC3** [Zuzu-Typ/PyGLM#220]
On https://pypi.org/project/PyGLM/, the "passing data to external libs" link goes to https://pypi.org/project/PyGLM/wiki/Passing-data-to-external-libs.md, which is a 404.

**Comment by Zuzu-Typ** [comment]
Hi @JC3,

Thank you for pointing this out.
I fixed the link in the README and it will be updated on PyPI upon the next release.
