### ISSUE TITLE
Pip3 install on raspberry pi freezes

### ISSUE THREAD

**Issue by raspb-robot-1324** [Zuzu-Typ/PyGLM#228]
I have an issue with pip3 install PyGLM. It works the first two minutes, then freezes at this install(when pip3 install -v PyGLM is used) : 

```
 glm/glm/./ext/../detail/type_vec4.hpp:17:9: note: 'glm::i16vec4' {aka 'struct glm::vec<4, short int, (glm::qualifier)0>'} declared here
    struct vec<4, T, Q>.

```

Any ideas on how to fix?
P.S: I'm using Raspberry pi 3B+
P.P.S: I've tried all know solutions listed on this forum and elsewhere. Nothing worked!

**Comment by Zuzu-Typ** [comment]
Hi there @raspb-robot-1324 ,

I believe this might be a memory issue. PyGLM requires a lot of memory to build and raspberry pis have limited RAM. That could be why it freezes too. piwheels.org has the same issue. I've contacted them, but I couldn't find exactly where.

I know too little about compilers and linux OSes to give you any substantial help. However, perhaps you can increase the swap size (if your sd card is large enough, and that is possible in raspbian without breaking anything).

Sorry I can't be of more help.

**Comment by Zuzu-Typ** [comment]
You might have luck with PyGLM version 1.1.7 or 0.5.3b1, which were the last versions that were built correctly by piwheels.org. Please have a look at their website, search for pyglm and look for previous releases, there you'll find some wheels that should work.
