### ISSUE TITLE
I am having problems building this on windows 7 or 10

### ISSUE THREAD

**Issue by shdwdln** [Zuzu-Typ/PyGLM#24]
I got the source and did a:
python setup.py build

and it said:
`pyglm.c(4) : fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory`

so I copied:
`#ifndef _STDBOOL_H
#define _STDBOOL_H

#ifndef __cplusplus

#define true 1
#define false 0
#define bool _Bool

#endif

#define __bool_true_false_are_defined 1

#endif
`
to C:\Python27\PC and now it returns a bunch of errors saying:

`c:\downloads\pyglm-master\glminternalfuncs.h(1148) : error C2143: syntax error : missing ';' before 'type'
c:\downloads\pyglm-master\glminternalfuncs.h(1149) : error C2065: 'oneOverLen' : undeclared identifier
c:\downloads\pyglm-master\glminternalfuncs.h(1149) : error C2065: 'oneOverLen' : undeclared identifier
c:\downloads\pyglm-master\glminternalfuncs.h(1149) : error C2065: 'oneOverLen' : undeclared identifier
c:\downloads\pyglm-master\glminternalfuncs.h(1149) : error C2065: 'oneOverLen' : undeclared identifier
c:\downloads\pyglm-master\glminternalfuncs.h(1160) : error C2061: syntax error : identifier 'iconjugate'r`

Any ideas what is going on?

**Comment by Zuzu-Typ** [comment]
Which compiler are you using?
Building the Python 2 version on Windows can be a bit challenging to get working, so don't be too hard on yourself.
