### ISSUE TITLE
types and functions not available via pip install pyglm

### ISSUE THREAD

**Issue by sina-masoud-ansari** [Zuzu-Typ/PyGLM#25]
```pip install pyglm```

Installed version via `glm.version()` is v0.3.6

```
import  glm
glm.mat4()
```

Results in `AttributeError: module 'glm' has no attribute 'mat4'`

Cloning this repo and installing via `python setup.py install` produces the expected output.

**Comment by Zuzu-Typ** [comment]
I think you might have accidentally installed "glm" instead of "pyglm", which is a totally different module.
PyGLM doesn't have the ```glm.version()``` constant and a version 0.3.6 never existed, however the latest version of glm is 0.3.6

**Comment by sina-masoud-ansari** [comment]
Correct! Apologies for the inconvenience.
