### ISSUE TITLE
Bug: axis angle to quat

### ISSUE THREAD

**Issue by hyperlogic** [Zuzu-Typ/PyGLM#261]
I was trying to generate quats from rotations specified via an axis and an angle and noticed an issue.

Not only is the result wrong (perhaps the components are swizzled), it is also not normalized.

Here is a test program demonstrating the problem.

```python
import glm
import math

def axis_angle_to_quat(axis, angle):
    n = glm.normalize(axis) * math.sin(angle / 2)
    w = math.cos(angle / 2)
    return glm.quat(w, n.x, n.y, n.z)

theta = math.pi / 8
q1 = axis_angle_to_quat(glm.vec3(0, 0, 1), theta)
print(q1)

q2 = glm.quat(theta, glm.vec3(0, 0, 1))
print(q2)
```

output:

```
quat(     0.980785,            0,            0,      0.19509 )
quat(     0.392699,            0,            0,            1 )
````

**Comment by Zuzu-Typ** [comment]
Hi @hyperlogic 

I believe there has been a misunderstanding.
Initializing a `quat` component wise, like `quat(w, x, y, z)` yields a quat with exactly those components. I.e.: `quat(w, x, y, z)`
or in your case: `quat(theta, vec3(0, 0, 1))`.

What you want is the [`angleAxis`](https://github.com/Zuzu-Typ/PyGLM/blob/master/wiki/function-reference/stable_extensions/quaternion_trigonometric.md#angleAxis-function) function.
Simply call
```Python
import glm

def axis_angle_to_quat(axis, angle):
    n = glm.normalize(axis) * glm.sin(angle / 2)
    w = glm.cos(angle / 2)
    return glm.quat(w, n.x, n.y, n.z)

theta = glm.pi() / 8
q1 = axis_angle_to_quat(glm.vec3(0, 0, 1), theta)
print(q1)

q2 = glm.angleAxis(theta, glm.vec3(0, 0, 1))
print(q2)
```
