### ISSUE TITLE
Add support for datatypes other than float

### ISSUE THREAD

**Issue by Zuzu-Typ** [Zuzu-Typ/PyGLM#27]
PyGLM should support more datatypes in the future, including custom ones using `vec<n, T, Q>`.

PyGLM should also support the precision qualifiers.

**Comment by pepcots** [comment]
I propose to use double precision as default type for all GLM types.
Great port!!

**Comment by Zuzu-Typ** [comment]
Thanks :)
I'd like to stick with the original glm's behaviour.

I'm not sure how far I should take this route, becuase I've already increased the library's file size by 10 times, just by adding doulbe, int8, int16, int32, int64 and bool vector datatypes.

The library loading time is also vastly increased, because each type has to be loaded at runtime.

I'm considering to publish these changes under a different name, such as "PyGLM-full" or something similar.
