### ISSUE TITLE
0.5.2b: compile failure on macOS (due to using clang?)

### ISSUE THREAD

**Issue by devernay** [Zuzu-Typ/PyGLM#29]
Hi,
`pip install pyglm` fails with all versions between 0.5.0b1 and 0.5.2b1 on macOS 10.13.6 with Xcode 10.1, see gist: https://gist.github.com/devernay/9601e4ad7c0a270b05e80016483a7810

Installing 0.4.8b1 with `pip install pyglm==0.4.8b1` succeeds.

My initial guess is that it is probably due to using clang to compile it.

**Comment by devernay** [comment]
Fixed it and created PR https://github.com/Zuzu-Typ/PyGLM/pull/30

**Comment by steve3d** [comment]
when can we expect this fixed new version?

**Comment by Zuzu-Typ** [comment]
It'll be a while until I've finished the update I'm currently working on.
I could theoretically push an update of the current version on the PyPI, although I don't see there being such a high demand for it.
You could try building from source otherwise

**Comment by wouterbt** [comment]
Thanks for the fix! I found this PR while looking for how to build PyGLM on macOS. I hope you can push this to PyPI, as it is easier to set up than building from source. Thanks!

**Comment by devernay** [comment]
@wouterbt  @steve3d you must also disable the frexp and ldexp functions to compile on macOS, or wait for a full fix. This can be done by installing from this fork https://github.com/devernay/PyGLM/tree/disable-frexp-ldexp or you can wait for a better solution if you need frexp and ldexp.

@Zuzu-Typ why not use travis-ci to build PyGLM on Linux and macOS, and appveyor to build it on Windows? That way every version would be guaranteed to built on the three systems. This is pretty simple to set up. I would be great to also have a small set of unit tests, at least to test the numerical functions.

**Comment by Zuzu-Typ** [comment]
I don't have any experience setting up a test suite, but I'll try once I find the time

**Comment by devernay** [comment]
It can be as simple as running a python script with a bunch of asserts inside, which you can run using `pytest` to get details about failures: https://docs.pytest.org/en/latest/

As for setting up travis, you just have to insert this simple .travis.yml at the root of the git, and enable the travis build:
https://docs.travis-ci.com/user/languages/python/
to enable multiple OS, see https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems

**Comment by Zuzu-Typ** [comment]
Thank you very much!
I'll look into that when I have spare time.

**Comment by steve3d** [comment]
And please also tag the same version on github， so we can know the detail changes between each version.
