### ISSUE TITLE
cross function returning always vec, not dvec

### ISSUE THREAD

**Issue by pepcots** [Zuzu-Typ/PyGLM#43]
cross function is always returning float vectors, not double.
```
a1 = glm.dvec3(random.random(), random.random(), random.random());
a2 = glm.dvec3(random.random(), random.random(), random.random());
a1
>>> dvec3( 0.784963, 0.180989, 0.458512 )
 a2
>>> dvec3( 0.291617, 0.296031, 0.0420636 )
glm.cross(a1,a2)
>>>vec3( -0.128121, 0.100692, 0.179594 )
```

**Comment by pepcots** [comment]
Well, it's happening with all functions. For example, glm.dot(dvec,dvec) returns a float, not double. Same with glm.length(dvec), etc...

**Comment by Zuzu-Typ** [comment]
It appears that I accidentally removed the type validity check from the `PyGLM_Vec_Check` macro, which is used every single time the type of a vector is checked. This can be easily fixed, however it might destroy some capabilities, where sometimes vectors of different types may no longer be interchangeable. I'll see what I can do.

By the way, I think you might have gotten carried away a little. 

> For example, glm.dot(dvec,dvec) returns a float, not double

There's no `double` in Python ^^'

**Comment by Zuzu-Typ** [comment]
Should be fixed now.

**Comment by pepcots** [comment]
> By the way, I think you might have gotten carried away a little.
> 
> > For example, glm.dot(dvec,dvec) returns a float, not double
> 
> There's no `double` in Python ^^'

I know! I did not explain well... what I mean is that you are losing precision.
For example
```
>>> v = glm.dvec3(1000000.000001, 0, 0);
>>> v.x
1000000.0
>>> v.x = 1000000.0000001
>>> v.x
1000000.0000001
>>> glm.length(v)
1000000.0
```

As you can see, you are losing precision on the constructor and you are losing precision when computing vector length.

I'm pretty sure everything is related with the macro as you said.

Many many thanks!

**Comment by pepcots** [comment]
With the new version I'm still losing precision with the constructor.
```
>>> v = glm.dvec3(1000000.0000001, 0, 0)
>>> v.x
1000000.0
>>> v.x = 1000000.0000001
>>> v.x
1000000.0000001
>>> glm.length(v.x)
1000000.0000001
>>> glm.length(v)
1000000.0000001
```

**Comment by pepcots** [comment]
But if I call constructor with a list, it works fine
```
>>> v = glm.dvec3([1000000.0000001, 0.0, 0.0]);
>>> v.x
1000000.0000001
```

**Comment by Zuzu-Typ** [comment]
You've actually spotted a major oversight in the vec3 constructor.
This happens only if any `vec3` that is not of type `float` is constructed with 
`(<number>, <number>, <number>)` or `(<vec2>, <number>)` or `(<number>, <vec2>)`.

Internally it's accidentally converted to a float vector (relict from the times when PyGLM didn't support other datatypes).

Writing a fix is as easy as replacing three `glm.vec3`'s with `glm.vec<3, T>`'s.
I will take care of that when I'm back home.
