### ISSUE TITLE
pyglm polar? 

### ISSUE THREAD

**Issue by Cazadorro** [Zuzu-Typ/PyGLM#47]
Is is possible to get the polar coordinate extension included? 

https://glm.g-truc.net/0.9.2/api/a00285.html

or is it not stable enough?

**Comment by Zuzu-Typ** [comment]
Hello Cazadorro,

the reason why experimental extensions were not included up until now, is the work that comes with their implementation.
It's simply not worth providing compatibility for a set of features that are likely to change in the future.

That said, adding support for single extensions on a one-by-one basis won't be a problem.
When I've got some spare time, I'll try to add this extension to PyGLM.

Maybe I'll even improve the documentation.

I can't promise, but I'll try.

**Comment by Zuzu-Typ** [comment]
Introduced in c2d87d674edb738ae0e59091db8eb1629a17071c
