### ISSUE TITLE
operator not equal in vec2 and vec3 return False for two different operand only if each component are different

### ISSUE THREAD

**Issue by phil-el** [Zuzu-Typ/PyGLM#5]
cut and copy error in vec3 and vec4 \_\_ne__

>> print(glm.vec4(1.0, 1.0, 1.0, 0.0) != glm.vec4(1.0, 1.0, 1.0, 1.0))
False

**Comment by Zuzu-Typ** [comment]
Fixed in https://github.com/Zuzu-Typ/PyGLM/commit/81cb35df863c553930e51a172cea50dd69fcc2ea .
