### ISSUE TITLE
manylinux and darwin wheels

### ISSUE THREAD

**Issue by einarf** [Zuzu-Typ/PyGLM#56]
It would be nice to have manylinux and macosx/darwin wheels on pypi. I guess it doesn't really matter too much for linux, but at least for darwin users it's not really straight forward to compile pyglm.

I'm a big fan of things working out of the box for win/linux/darwin for all my pacakges, so this is might an improvement to look into. Ci systems can do this today as well.

**Comment by aforren1** [comment]
Hah, I *just* starting trying this out; see https://github.com/aforren1/PyGLM/tree/ci. It uses [cibuildwheel](https://github.com/joerick/cibuildwheel/) to build wheels across all platforms. All successfully build & pass tests, but haven't worked out uploading them anywhere...

**Comment by aforren1** [comment]
Testing wheels here: https://github.com/aforren1/PyGLM/releases/tag/testing

**Comment by Zuzu-Typ** [comment]
It's looking pretty nice already!
Great work 👍 

I hope you don't mind me pulling it over to the [build-win-linux-mac](https://github.com/Zuzu-Typ/PyGLM/tree/build-wheel-win-linux-mac) branch, trying to get it to run on my end as well

**Comment by einarf** [comment]
Tried a few of the OS X wheel. Worked!

**Comment by Zuzu-Typ** [comment]
Seems to work like a charm now.

Thanks again @aforren1, I wouldn't have been able to accomplish this without you (: 

Now I only need to find a way to upload the files to the PyPI without too much manual work. 😅

**Comment by aforren1** [comment]
I think you can also feed in PyPI credentials as part of the process? e.g. https://github.com/joerick/cibuildwheel/blob/master/examples/travis-ci-deploy-only.yml

**Comment by einarf** [comment]
Absolutely awesome. I can use this library in moderngl examples and moderngl-window now 😄

**Comment by Zuzu-Typ** [comment]
> I think you can also feed in PyPI credentials as part of the process? e.g. https://github.com/joerick/cibuildwheel/blob/master/examples/travis-ci-deploy-only.yml

It might work now. Only the future can tell (:

**Comment by einarf** [comment]
Got it working in the glcontext project : https://github.com/moderngl/glcontext
I'm just adding the PyPI token in the env config on travis-ci (for all branches so tags are included)
