### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Zuzu-Typ** [Zuzu-Typ/PyGLM#6]
There are a bunch of memory leaks hidden somewhere in PyGLM.

Please locate and fix them.

Best of luck!
~_me_

**Comment by phil-el** [comment]
Ha, I had a different fix for all these https://github.com/phil-el/PyGLM/commit/2c2b7c46ceeef23a2519c2cb937972790c6e7aef

**Comment by Zuzu-Typ** [comment]
That's what I did at first, but when I realized I had built these vectors, just so they were unpacked during the creation of the matrix, I decided to remove this _ineffectiveness_ and initialize it with doubles.
Thanks anyway ;)

**Comment by phil-el** [comment]
but this way there is no way to reuse the temporary created by c = a + b ?  (mat4 type for example), actually it unpack then repack to do the assignment, isn't the inefficiency coming from the way matrix are created? 

tbh even a better way will be to cheat with python refcount and to do a transfer of ownership for the temporary, unsure if it's possible in python. I've not checked it but looking at the code, at least for basic ops like + - etc. creation of the object is the most costly part, vectorization will not help a lot.

**Comment by Zuzu-Typ** [comment]
I'm not sure I get what you're saying.
in the __add__ function of glm::detail::tmat4x4 the temporary variables **o** and **o2** of type _imat4x4_ are used.
The reason for this is so you can use either a matrix, or a matrix-like tuple or list, which cannot be converted to a _tmat4x4*_.

The internal functions for repacking convert a given set of doubles back to a _PyObject*_ (to be Python-compatible). In the process it calls the respective __init__ function with the supplied doubles as the argument.
Originally I thought I would just pack the vectors of the matrix (as in your version) and make the __init__ function replace the matrix' current ones.
The problem with that though would be that if you initialized a matrix with existing vectors, these would be changed if the matrix is changed -- which is not intended (and not the way the actual GLM works).

**Comment by phil-el** [comment]
I was thinking about unnecessary call to typexxxx_init() function but after adding some printf I see there is none such call. But I was thinking too about your point, pack_tmat4x4 convert double to python object then \_\_init__ convert back to double this is where most of cpu time is used, I've some profiling showing that if you are interested though I've no detailed profiling for python run-time itself, only glm shared libs. We are going far from the original subject of this issue.

**Comment by Zuzu-Typ** [comment]
This is probably the most efficient way of pack_*-ing

**Comment by phil-el** [comment]
Nice, more than four time faster, dumped profiling result before/after this commit https://gist.github.com/phil-el/45d22660d8d7585cba283d7d87665855

**Comment by phil-el** [comment]
Errm, python3 is fine but python2 leak as hell with this commit.

**Comment by Zuzu-Typ** [comment]
That's really odd, because it doesn't on my end.
I'm using a Windows machine, with pyglm built using MinGW. There are no additional memory leaks.
However, I've encountered a bunch more issues with \_\_iadd\_\_, where it creates wrong results or crashes when supplied certain arguments. 

If this issue persists, would you be so kind to open up a new issue thread?

**Comment by phil-el** [comment]
do you still have trouble with \_\_iadd__?

**Comment by Zuzu-Typ** [comment]
As I had already suspected it was due to an earlier commit which fixed this exact issue (apparently for Python 3 only). A quick fix made up for that.

**Comment by phil-el** [comment]
See also issue https://github.com/Zuzu-Typ/PyGLM/issues/16, a segfault with python 2.7 when using vec4 iterator but which leak with python3. Probably the same bug.

**Comment by Zuzu-Typ** [comment]
That's all of the memory leaks I (and my testing-script) have found.
Reopen if necessary.
