### ISSUE TITLE
PyGLM types do not support `PyBUF_SIMPLE`

### ISSUE THREAD

**Issue by einarf** [Zuzu-Typ/PyGLM#61]
Example from `mat_getbuffer`
```cpp
if ((flags & PyBUF_RECORDS_RO) != PyBUF_RECORDS_RO || (flags & PyBUF_F_CONTIGUOUS) == PyBUF_F_CONTIGUOUS || (flags & PyBUF_ANY_CONTIGUOUS) == PyBUF_ANY_CONTIGUOUS) {
	PyErr_SetString(PyExc_BufferError, "This type of buffer is not supported.");
	view->obj = NULL;
	return -1;
}
```

Most types (if not all) do pass the `PyBuffer_IsContiguous()` tests, so I assume all types have contiguous buffer data. Still, the various `*_getbuffer` methods do not accept this flag.

We discovered this issue when trying to set uniform or buffer data in moderngl.
```
program['uniform'].value = (1, 1, 1)    # working
program['uniform'].write(np.array([1,1,1]))    # working

v = glm.fvec3(1,1,1)
program['uniform'].write(memoryview(v))    # working
program['uniform'].write(bytes(v))    # working
program['uniform'].write(np.array(v))    # working

program['uniform'].write(v)    #  <--------- error
```
Error output:
```
BufferError: This type of buffer is not supported.
```

We obtain the buffer using:
```
PyObject_GetBuffer(value, &buffer_view, PyBUF_SIMPLE);
```
This is acceptable when you just want to write contiguous to an opengl buffer and have no plans to keep the buffer reference or modify it.

More details here:
https://github.com/moderngl/moderngl/issues/379

**Comment by Zuzu-Typ** [comment]
I'm not sure I understand what you're getting at.

> Most types (if not all) do pass the PyBuffer_IsContiguous() tests, so I assume all types have contiguous buffer data. Still, the various *_getbuffer methods do not accept this flag.

`PyBUF_SIMPLE` has nothing to do with contiguity. It's about the structure of the data (see [here](https://docs.python.org/3/c-api/buffer.html#shape-strides-suboffsets)).

It doesn't make sense to me for PyGLM to provide buffers with less complexity than `PyBUF_STRIDES`.
The buffers it provides needs to provide information about the shape (e.g. `(4, 4)` for `mat4x4`) and stride (e.g. `sizeof(double)` for `dmat4x4`). Otherwise the buffer data would be useless (unless the calling function knew the shape anyway).

PyGLM accepts any buffer requests that have at least the `PyBUF_RECORDS_RO` flag and not fortan contiguity (because the data is layed out in C contiguity).

**Comment by Zuzu-Typ** [comment]
I guess I could add support for less complex buffer structures in case a program wants that.

**Comment by einarf** [comment]
Sorry, I was rambling a but trying to figure things out with zero assumptions 😄 

Yes it would definitely be nice to have support for less complex buffer structures so they can be used just like `memoryview`, `bytes` and np arrays.

**Comment by einarf** [comment]
Works now. Thank you.

**Comment by aforren1** [comment]
It looks like a6c0f1f1c1d185add357203ce3165b71a7eedb45 introduced a strides check, so `PyBUF_SIMPLE` requests don't seem to work from v2.0.0a3 onward. Any chance that check can be removed so `PyBUF_SIMPLE` works again, or am I missing some other detail? Thanks!

**Comment by Zuzu-Typ** [comment]
> It looks like [a6c0f1f](https://github.com/Zuzu-Typ/PyGLM/commit/a6c0f1f1c1d185add357203ce3165b71a7eedb45) introduced a strides check, so `PyBUF_SIMPLE` requests don't seem to work from v2.0.0a3 onward. Any chance that check can be removed so `PyBUF_SIMPLE` works again, or am I missing some other detail? Thanks!

I don't know why exactly I added that check back in. 
I'll fix it right away.
Thanks for letting me know (:

**Comment by aforren1** [comment]
Great, thanks for the fix!

**Comment by einarf** [comment]
Thanks! I just noticed this late last night when upgrading pyglm. Writing uniform data to shaders did not work any more in moderngl and arcade using the buffer protocol.
