### ISSUE TITLE
support for L1, Linf norm

### ISSUE THREAD

**Issue by jimy-byerley** [Zuzu-Typ/PyGLM#63]
Is that possible to add a norm function to use the L1 and L infinite norms instead of L2 (euclidian norm) ?
These norms have often the advantage of being faster (no float product and square root)

Something like  `norm1`, `norminf` or `length1`, `lengthinf`
Then for coherence, it would be nice to define an alias to the current `length` function named along `length2` or `norm2`

**Comment by Zuzu-Typ** [comment]
If you want to request features that aren't present in [glm](https://glm.g-truc.net/0.9.9/index.html) itself, please do so over [here](https://github.com/g-truc/glm/issues).
Until then, feel free to use these lambdas:
```Python
norm1 = lambda v: sum(abs(v))
norminf = lambda v: max(abs(v))
```

**Comment by jimy-byerley** [comment]
Oh sorry, yes. I'm on the wrong repo.

**Comment by Zuzu-Typ** [comment]
I see, it's one of the experimental extensions.
I'm sure it'll make it in when I have some time.
