### ISSUE TITLE
numpy conversion from list of vec or mat

### ISSUE THREAD

**Issue by jimy-byerley** [Zuzu-Typ/PyGLM#64]
Converting a list of vec to numpy array produces an error (I guess in the iterator protocol)
```python
numpy.array([vec3(1,0,0), vec3(0,1,0)])
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'vec3Iter' object is not iterable
```
The same happends for `vec2` and `vec4` of course

Converting a list of mat to numpy array produces a more weirded error
```python
numpy.array([mat2(1), mat2(0)])
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: could not convert string to float: mat2x2( 1, 0 | 0, 1 )
```

As the vec and mat are iterables (iterable over iterables for mat), they should be able to work with the numpy array function, right ?

**Comment by Zuzu-Typ** [comment]
> As the vec and mat are iterables (iterable over iterables for mat), they should be able to work with the numpy array function, right ?

They do, as long as they're not inside a list.
The way numpy is implemented, it doesn't really work with iterables in lists (especially for iterables that return iterables, such as mat2).
It's simply a design choice, probably for performance and reliability reasons.

You can convert each of them to a list though.
```Python
numpy.array([mat2(1).to_list(), mat2(0).to_list()])
```
