### ISSUE TITLE
Crash when dividing by zero

### ISSUE THREAD

**Issue by alexcher-im** [Zuzu-Typ/PyGLM#65]
When i do `ivec2(1) / ivec2(0)` or any other division of int vector by 0 python crashes:
`Process finished with exit code -1073741676 (0xC0000094)`

P.S. PyGLM version: 1.1.8, latest pypi version for now.

**Comment by Zuzu-Typ** [comment]
Haha, well - believe it or not, it's actually causing a simple division by zero error that isn't handled.
Thus it crashes.
I'll release a fix once I have some more free time

**Comment by alexcher-im** [comment]
Sorry, i didn't notice it was not segfault :D
