### ISSUE TITLE
Windows builds aren't deployed

### ISSUE THREAD

**Issue by Zuzu-Typ** [Zuzu-Typ/PyGLM#70]
There seems to be an ongoing issue on Travis CI, due to which PyGLM's Windows builds aren't uploaded.
I've already contacted their support team.

Hopefully this can be quickly resolved so the windows users out there don't have to wait for v1.2.0 to deploy much longer.

Cheers
--Zuzu_Typ--

**Comment by aforren1** [comment]
Changing the language from `generic` to `bash` at line https://github.com/Zuzu-Typ/PyGLM/blob/master/.travis.yml#L20 seems to be a workaround-- found the tip [here](https://travis-ci.community/t/windows-vm-not-booting/1068/8), and it worked for one of my pet projects.

**Comment by einarf** [comment]
I have the same problem as well on a few projects. I thought it was related to api key, but haven't looked closer at it.

**Comment by Zuzu-Typ** [comment]
Thank you very much @aforren1 :)
