### ISSUE TITLE
Passing glm.mat4 from Python back to C++ (glm::mat4)

### ISSUE THREAD

**Issue by jackw1111** [Zuzu-Typ/PyGLM#78]
I have a boost python application that exports a class to Python, performs a calculation and returns the output back to C++:

```
import engine # c++ library
import glm # pyglm

class Game(engine.Application):
    def __init__(self):
        engine.Application.__init__(self, title, fullscreen)
        self.shader = engine.Shader();
        self.shader.setup("shader.vs", "shader.fs")
        self.shader.setMat4("model", glm.mat4(1.0)
    def update(self):
        ...
```

Amongst other classes, the shader is being wrapped and exported from C++ like this:

```
struct ShaderWrap : Shader, boost::python::wrapper<Shader>
{
  int setup(const char* vertexPath, const char* fragmentPath)
  {
    return Shader::setup(vertexPath, fragmentPath);
  }
  int setMat4(std::string name, glm::mat4 mat)
  {
    return Shader::setMat4(name, mat);
  }
};

...

BOOST_PYTHON_MODULE(engine)
{
  namespace python = boost::python;

  ...


  python::class_<ShaderWrap, boost::noncopyable>("Shader")
    .def("setup", &Shader::setup)
    .def("setMat4", &Shader::setMat4)
    ;

  ...
}
```
The application works fine up until the `self.shader.setMat4` call and I get the error:

```
Boost.Python.ArgumentError: Python argument types in
    StaticShader.setMat4(StaticShader, str, glm::detail::tmat4x4)
did not match C++ signature:
    setMat4(StaticShader {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, glm::mat<4, 4, float, (glm::qualifier)0>)
```

I've tried to pass the `mat4` value as a `float*` back to C++ with no success. I've also tried calling `value_ptr(mat4)` which returns a `c_void_p`, but the compiler complains saying `c_void_p` and `void*` are not the same type (also tried various attempts of casting it with the `ctypes` library).

In the `PyGLM` documentation, the developer says the library is written in C++. So,

**What would be a possible way to pass through a `glm.mat4` value to C++ to be interpreted as a `glm::mat4` value?**

I want to pass a `glm.mat4` such as the view matrix, being updated in the Python code update function back to C++ to be further used, and was hoping there would be a fairly simple interface between the pyGLM library/GLM library through boost::python. **Apologies if this isn't the best place to ask this question, but I couldn't find much help anywhere else. Thanks in advance.**

**Comment by Zuzu-Typ** [comment]
Hi there jackw1111,

unfortunately I haven't used boost::python before, so there isn't much I can do to help you.

This is what matrix objects look like in C++ code:
```C++
template<int C, int R, typename T>
struct mat {
	PyObject ob_base;
	uint8_t info;
	glm::mat<C, R, T> super_type;
};
```
That is most likely why it's not quite compatible to glm matrices.

If you're using the latest version of PyGLM, `value_ptr(mat4)` should return a `LP_c_float` object, i.e. a  `float*`.
I'm sure there is a way to transfer such a pointer over to boost::python, though as I said, I don't know how.

Technically you could convert the pointer to an integer, transfer that and cast it back to a `float*`.
You can get the address of a pointer by using:
```Python
int.from_bytes(ptr, "little")
```

Alternatively you could simply send over a bytes object.
```Python
as_bytes = bytes(mat4)
```

Or as a tuple:
```Python
as_tuple = mat4.to_tuple()
```

Or as a numpy array (which seems to have it's own boost::python::numpy module):
```Python
np_arr = numpy.array(mat4)
```

Sorry for your inconvenience

**Comment by jackw1111** [comment]
Hi Zuzu-Typ,

Thanks for the fast reply.
This is all good information and gives me some good leads to try. I am still learning the ropes of Boost as well but it seems the PyObject* could be useful, or as you said, value_ptr returning a float*, otherwise yes I will try passing the pointer as an int. Thank-you for the info!

Sent from my iPhone

On 21 Jun 2020, at 8:06 PM, Zuzu-Typ <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there jackw1111,

unfortunately I haven't used boost::python before, so there isn't much I can do to help you.

This is what matrix objects look like in C++ code:

template<int C, int R, typename T>
struct mat {
        PyObject ob_base;
        uint8_t info;
        glm::mat<C, R, T> super_type;
};

That is most likely why it's not quite compatible to glm matrices.

If you're using the latest version of PyGLM, value_ptr(mat4) should return a LP_c_float object, i.e. a float*.
I'm sure there is a way to transfer such a pointer over to boost::python, though as I said, I don't know how.

Technically you could convert the pointer to an integer, transfer that and cast it back to a float*.
You can get the address of a pointer by using:

int.from_bytes(ptr, "little")

Alternatively you could simply send over a bytes object.

as_bytes = bytes(mat4)

Or as a tuple:

as_tuple = mat4.to_tuple()

Or as a numpy array (which seems to have it's own boost::python::numpy module):

np_arr = numpy.array(mat4)

Sorry for your inconvenience
