### ISSUE TITLE
glm.angle() returns wrong value

### ISSUE THREAD

**Issue by nir** [Zuzu-Typ/PyGLM#90]
In version 1.99.2 of PyGLM calling:
> glm.angle(glm.angleAxis(5.2832, (0, 0, 1))) 

returns:
> 0.9999855160713196

Using Windows 10 + python 3.7

**Comment by Zuzu-Typ** [comment]
Hello nir,

I've looked at the code and found, that in [quaternion_trigonometric.inl](https://github.com/g-truc/glm/blob/master/glm/ext/quaternion_trigonometric.inl#L8-L13), the angle is computed like this:
```C++
T angle(qua<T, Q> const& x)
{
	if (abs(x.w) > cos_one_over_two<T>())
	{
		return asin(sqrt(x.x * x.x + x.y * x.y + x.z * x.z)) * static_cast<T>(2);
	}
	return acos(x.w) * static_cast<T>(2);
}
```
Where `cos_one_over_two<T>()` is equal to `0.877582561890372716130286068203503191`.

`angleAxis(5.2832, (0, 0, 1))` returns `quat( -0.877586, 0, 0, 0.479419 )`, thus the absolute value of the `w` component is not smaller than `cos_one_over_two<T>()` and it computes the value differently.

I'm not sure why it's done that way, however, this issue belongs to [g-truc/glm](https://github.com/g-truc/glm) (where there is no longer an issue tracker unfortunately).

However, the returned angle is always the reverse angle of the specified one (i.e. if you added the returned value to your input value you would end up with a full turn).
```Python
>>> 0.9999855160713196 + 5.2832
6.2831855160713195

>>> 2 * pi()
6.283185307179586
```

Cheers
--Zuzu_Typ--
