### ISSUE TITLE
No way to seed random functions

### ISSUE THREAD

**Issue by serin-delaunay** [Zuzu-Typ/PyGLM#97]
I called `glm.gaussRand(0.0, 1.0)` a few times in my code and got the same values each time I ran the program. I tried calling the Python builtin `random.seed()` but it didn't affect the GLM values. I can't find a `seed()` or `srand()` function in the PyGLM docs.

**Comment by Zuzu-Typ** [comment]
Hi there Serin,

yes, you are correct there is currently no way to set the seed for glm's random functions, which use `std::rand` to generate pseudo-random-numbers.

I will add a `glm.seed` or `glm.srand` function in the future to address this issue.

Thank you for letting me know.
